# Generated by Django 5.2.9 on 2025-12-12 22:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Barrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('CERRADA', 'CERRADA')], default='CERRADA', max_length=10)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='barrera', to='api.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('nombre', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(3)])),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('MANTENCION', 'MANTENCION')], default='ACTIVO', max_length=12)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensores', to='api.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('PERMITIDO', 'PERMITIDO'), ('DENEGADO', 'DENEGADO')], max_length=10)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='api.departamento')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='api.sensor')),
            ],
        ),
    ]
